export interface CatalogProduct {
  id: string
  name: string
  description: string
  price: number // in paise
  category: 'SPARKLERS' | 'ROCKETS' | 'FLOWERPOTS' | 'CHAKRAS' | 'COMBO_PACKS' | 'FOUNTAINS' | 'BOMBS' | 'FANCY_ITEMS'
  imageUrl: string
  stockQuantity: number
  isActive: boolean
}

export const FALLBACK_PRODUCTS: CatalogProduct[] = [
  {
    id: 'prod-spk-1',
    name: '10cm Electric Sparklers (Box of 10)',
    description: 'Classic dazzling golden electric sparklers with crackling sound. Safe for kids with adult supervision. Burn time: 45 seconds each.',
    price: 8500,
    category: 'SPARKLERS',
    imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=600&q=80',
    stockQuantity: 150,
    isActive: true,
  },
  {
    id: 'prod-spk-2',
    name: '15cm Multi-Color Sparklers (Box of 10)',
    description: 'Vibrant sparklers that emit dazzling flashes of red, green, and gold. High grade magnesium wires.',
    price: 14000,
    category: 'SPARKLERS',
    imageUrl: 'https://images.unsplash.com/photo-1498931299472-f7a63a5a1cfa?w=600&q=80',
    stockQuantity: 120,
    isActive: true,
  },
  {
    id: 'prod-spk-3',
    name: '30cm Giant Gold Sparklers (Box of 5)',
    description: 'Extra long sparkling display lasting over 2 minutes per stick. Perfect for family celebrations and memorable photos.',
    price: 22000,
    category: 'SPARKLERS',
    imageUrl: 'https://images.unsplash.com/photo-1531747056595-07f6cbbe10ad?w=600&q=80',
    stockQuantity: 80,
    isActive: true,
  },
  {
    id: 'prod-chk-1',
    name: 'Ground Chakkars Deluxe (Pack of 10)',
    description: 'Fast-spinning ground wheels creating mesmerizing spirals of silver and gold fire rings.',
    price: 18000,
    category: 'CHAKRAS',
    imageUrl: 'https://images.unsplash.com/photo-1533230307785-5fe068595eb2?w=600&q=80',
    stockQuantity: 100,
    isActive: true,
  },
  {
    id: 'prod-chk-2',
    name: 'Special Red & Green Whirlwind Chakkars (Pack of 10)',
    description: 'Dual-speed rotating disc that changes from ruby red to emerald green with crackling sparks.',
    price: 26000,
    category: 'CHAKRAS',
    imageUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&q=80',
    stockQuantity: 75,
    isActive: true,
  },
  {
    id: 'prod-fp-1',
    name: 'Flowerpot Big Golden Shower (Pack of 10)',
    description: 'Grand fountain shooting gold stars up to 10 feet with a crackling finale.',
    price: 29000,
    category: 'FLOWERPOTS',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&q=80',
    stockQuantity: 90,
    isActive: true,
  },
  {
    id: 'prod-fp-2',
    name: 'Color Fountain Flowerpots (Pack of 5)',
    description: 'Emits intense shades of purple, green, lemon yellow, and crimson red up to 12 feet high.',
    price: 36000,
    category: 'FLOWERPOTS',
    imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=600&q=80',
    stockQuantity: 60,
    isActive: true,
  },
  {
    id: 'prod-rkt-1',
    name: 'Sky Whistle Rockets (Pack of 10)',
    description: 'High velocity screamers that ascend with a loud siren screech and burst into a silver umbrella.',
    price: 32000,
    category: 'ROCKETS',
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600&q=80',
    stockQuantity: 85,
    isActive: true,
  },
  {
    id: 'prod-rkt-2',
    name: 'Parachute Sky Shot Rockets (Pack of 5)',
    description: 'Launches 80 feet into the night sky, releasing an illuminated glowing parachute gently floating down.',
    price: 45000,
    category: 'ROCKETS',
    imageUrl: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=600&q=80',
    stockQuantity: 40,
    isActive: true,
  },
  {
    id: 'prod-rkt-3',
    name: 'Mega Galaxy Rockets 3-Stage (Pack of 3)',
    description: 'Triple burst heavy rockets with gold willow, ruby peony, and crackling brocade crown.',
    price: 59000,
    category: 'ROCKETS',
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600&q=80',
    stockQuantity: 30,
    isActive: true,
  },
  {
    id: 'prod-fnt-1',
    name: 'Peacock 7-Color Fountain (Single Box)',
    description: 'Magnificent conic fountain imitating a strutting peacock fan with 7 shifting colors and low smoke.',
    price: 34000,
    category: 'FOUNTAINS',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&q=80',
    stockQuantity: 50,
    isActive: true,
  },
  {
    id: 'prod-fnt-2',
    name: 'Silver Cascade Niagara Waterfall (Single)',
    description: 'Massive silver sparks waterfall cascading continuous sparks for over 90 seconds.',
    price: 42000,
    category: 'FOUNTAINS',
    imageUrl: 'https://images.unsplash.com/photo-1533230307785-5fe068595eb2?w=600&q=80',
    stockQuantity: 45,
    isActive: true,
  },
  {
    id: 'prod-bmb-1',
    name: 'Classic 28 Chorsa Crackers (Pack of 5 strings)',
    description: 'Traditional rhythmic red paper firecrackers delivering classic Diwali festive sound and auspicious energy.',
    price: 19000,
    category: 'BOMBS',
    imageUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&q=80',
    stockQuantity: 110,
    isActive: true,
  },
  {
    id: 'prod-bmb-2',
    name: 'Hydro Green Sound King (Pack of 10)',
    description: 'Eco-certified green formula loud sound cracker compliant with low-emission standards.',
    price: 25000,
    category: 'BOMBS',
    imageUrl: 'https://images.unsplash.com/photo-1531747056595-07f6cbbe10ad?w=600&q=80',
    stockQuantity: 95,
    isActive: true,
  },
  {
    id: 'prod-bmb-3',
    name: 'Thunderbolt Mega Sound Shells (Pack of 5)',
    description: 'Heavy bass sonic boom crackers with intense reverberation. For open grounds only.',
    price: 38000,
    category: 'BOMBS',
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600&q=80',
    stockQuantity: 0, // Demonstrates out-of-stock badge
    isActive: true,
  },
  {
    id: 'prod-fnc-1',
    name: '12 Shots Aerial Multi-Color Cake',
    description: 'Rapid sequential battery shooting 12 colorful aerial comets bursting into chrysanthemums.',
    price: 75000,
    category: 'FANCY_ITEMS',
    imageUrl: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=600&q=80',
    stockQuantity: 40,
    isActive: true,
  },
  {
    id: 'prod-fnc-2',
    name: '30 Shots Golden Willow Sky Spectacular',
    description: 'Professional grade mini display box. Shoots 30 golden weeping willow comets lighting the whole sky.',
    price: 165000,
    category: 'FANCY_ITEMS',
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600&q=80',
    stockQuantity: 25,
    isActive: true,
  },
  {
    id: 'prod-fnc-3',
    name: 'Spinning Butterfly Flying Saucer (Pack of 10)',
    description: 'Whirling spinners that lift off vertically spinning with bright green lights and a soft crackle.',
    price: 27000,
    category: 'FANCY_ITEMS',
    imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=600&q=80',
    stockQuantity: 65,
    isActive: true,
  },
  {
    id: 'prod-cmb-1',
    name: 'Kids Safety Diwali Joy Hamper (18 Items)',
    description: 'Specially curated kid-friendly safe box containing sparklers, ground chakras, pencil fountains, and snake tablets.',
    price: 99900,
    category: 'COMBO_PACKS',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&q=80',
    stockQuantity: 50,
    isActive: true,
  },
  {
    id: 'prod-cmb-2',
    name: 'Family Celebration Grand Pack (35 Items)',
    description: 'Complete family package with a balanced mix of sparklers, chakkars, pots, whistling rockets, and aerial shots.',
    price: 249900,
    category: 'COMBO_PACKS',
    imageUrl: 'https://images.unsplash.com/photo-1533230307785-5fe068595eb2?w=600&q=80',
    stockQuantity: 35,
    isActive: true,
  },
  {
    id: 'prod-cmb-3',
    name: 'Royal VIP Display Box (60 Premium Items)',
    description: 'Ultimate festival collection featuring 50-shot aerial cakes, giant waterfalls, tri-color flowerpots, and premium sparklers.',
    price: 499900,
    category: 'COMBO_PACKS',
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=600&q=80',
    stockQuantity: 20,
    isActive: true,
  },
]
